### ISSUE TITLE
Must supply cloud_name issue

### ISSUE THREAD

**Issue by newtoneweb** [Mohamed-Elbehery/Food_Booking_Backend#1]
environment variable is CLOUDINARY_CLOUD_NAME not CLOUDINARY_NAME in utils/cloudinary.ts
change this.
cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
thx

**Comment by Mohamed-El-Sharqawy** [comment]
Thanks for your contribution I really appreciate it because I didn't notice it in the readme.md

I have edited it.
